services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - jellyfin-config:/config
      - /mnt/NC/eric/files/filme/:/media
    ports:
      - 90:8096
    restart: unless-stopped
volumes:
  jellyfin-config:
