services:
  npmplus:
    container_name: npmplus
    image: 'zoeyvid/npmplus'
    restart: unless-stopped
    volumes:
      - /opt/npm:/data
      - ./letsencrypt:/etc/letsencrypt
    network_mode: host
    environment:
      - TZ=Europe/Berlin
      - NPM_PORT=81
      - LOGROTATE=true
